//! communication_middleware — LPUART / FlexIO UART middleware for the S32K344.
//!
//! This module provides safe, idiomatic Rust wrappers around the NXP RTD
//! `Lpuart_Uart_Ip` and `Flexio_Uart_Ip` IP-layer drivers that are declared in
//! [`crate::ffi`].
//!
//! # Architecture
//!
//! ```text
//!  ┌──────────────────────────────────────────┐
//!  │              Application code             │
//!  └─────────────────┬────────────────────────┘
//!                    │  safe API
//!  ┌─────────────────▼────────────────────────┐
//!  │        communication_middleware           │
//!  │  init / deinit / send_data / receive_data │
//!  └─────────────────┬────────────────────────┘
//!                    │  unsafe FFI
//!  ┌─────────────────▼────────────────────────┐
//!  │  ffi.rs   ──   C RTD driver layer        │
//!  │  Lpuart_Uart_Ip_*  /  Flexio_Uart_Ip_*   │
//!  └──────────────────────────────────────────┘
//! ```
//!
//! # Hardware channel assignments
//!
//! These match the definitions used in the
//! `LpuartFlexio_Uart_Ip_Example_S32K344` reference project:
//!
//! | Constant            | Value | Description                |
//! |---------------------|-------|----------------------------|
//! | `LPUART_CHANNEL`    | 3     | LPUART instance 3          |
//! | `FLEXIO_TX_CHANNEL` | 0     | FlexIO UART transmit ch. 0 |
//! | `FLEXIO_RX_CHANNEL` | 1     | FlexIO UART receive  ch. 1 |
//!
//! # Adding support for new channels
//!
//! 1. Extend [`UartBackend`] with the new variant.
//! 2. Add a corresponding arm to the `match` in [`send_data`] / [`receive_data`].
//! 3. Declare any additional C functions in `ffi.rs`.

use crate::ffi::{
    FlexioStatus, FlexioUserConfig, Flexio_Uart_Ip_AsyncReceive, Flexio_Uart_Ip_AsyncSend,
    Flexio_Uart_Ip_Deinit, Flexio_Uart_Ip_GetStatus, Flexio_Uart_Ip_Init, FormatKeyCatalogs_,
    IsKeyCatalogFormatted, LpuartStatus, LpuartUserConfig, Lpuart_Uart_Ip_AsyncReceive,
    Lpuart_Uart_Ip_AsyncSend, Lpuart_Uart_Ip_Deinit, Lpuart_Uart_Ip_GetReceiveStatus,
    Lpuart_Uart_Ip_GetTransmitStatus, Lpuart_Uart_Ip_Init, ParseKeyCatalogs,
    RAM_AES_GROUP1_SLOT0, RAM_AES_GROUP1_SLOT1,
};
use crate::hse::{self, HseError, key_flags};
use core::sync::atomic::{AtomicU32, Ordering};

// =============================================================================
// Channel constants — match LpuartFlexio_Uart_Ip_Example_S32K344 / main.c
// =============================================================================

/// LPUART hardware instance number used by this middleware.
pub const LPUART_CHANNEL: u8 = 3;

/// FlexIO channel configured as UART transmitter.
pub const FLEXIO_TX_CHANNEL: u8 = 0;

/// FlexIO channel configured as UART receiver.
pub const FLEXIO_RX_CHANNEL: u8 = 1;

/// Busy-poll iteration limit. Prevents infinite loops on hardware faults.
const POLL_TIMEOUT: u32 = 0x00FF_FFFF;

// =============================================================================
// Public API types
// =============================================================================

/// Selects the physical UART backend for a [`send_data`] or [`receive_data`] call.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum UartBackend {
    /// Operate via the LPUART peripheral (instance [`LPUART_CHANNEL`]).
    Lpuart,
    /// Operate via the FlexIO UART transmitter channel ([`FLEXIO_TX_CHANNEL`]).
    FlexioTx,
    /// Operate via the FlexIO UART receiver channel ([`FLEXIO_RX_CHANNEL`]).
    FlexioRx,
}

/// Errors returned by the communication-middleware layer.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum CommError {
    /// A zero-length buffer was passed to the function.
    InvalidArgument,
    /// The LPUART driver returned a non-success, non-busy status.
    LpuartError(LpuartStatus),
    /// The FlexIO UART driver returned a non-success, non-busy status.
    FlexioError(FlexioStatus),
    /// The busy-poll loop reached [`POLL_TIMEOUT`] iterations without completing.
    PollTimeout,
    /// [`send_data`] was called with [`UartBackend::FlexioRx`] (receive-only),
    /// or [`receive_data`] was called with [`UartBackend::FlexioTx`] (transmit-only).
    WrongDirection,
}

// =============================================================================
// Initialization / deinitialization
// =============================================================================

/// Initialises the LPUART instance and both FlexIO UART channels.
///
/// Must be called once — before any [`send_data`] or [`receive_data`] call —
/// after the clock and pin-mux layers are already configured.  Call [`deinit`]
/// when the middleware is no longer needed.
///
/// The config pointers must remain valid for the full lifetime of the driver;
/// they are typically the `extern` constants generated by the BSW configuration
/// tool (e.g. `&Lpuart_Uart_Ip_xHwConfigPB_3_VS_0`).
///
/// # Safety
///
/// * `lpuart_config` must point to a valid `Lpuart_Uart_Ip_UserConfigType`.
/// * `flexio_tx_config` / `flexio_rx_config` must each point to a valid
///   `Flexio_Uart_Ip_UserConfigType`.
/// * Calling `init` more than once without an intervening `deinit` is
///   undefined behaviour in the underlying C driver.
pub unsafe fn init(
    lpuart_config: *const LpuartUserConfig,
    flexio_tx_config: *const FlexioUserConfig,
    flexio_rx_config: *const FlexioUserConfig,
) {
    Lpuart_Uart_Ip_Init(LPUART_CHANNEL, lpuart_config);
    Flexio_Uart_Ip_Init(FLEXIO_TX_CHANNEL, flexio_tx_config);
    Flexio_Uart_Ip_Init(FLEXIO_RX_CHANNEL, flexio_rx_config);
}

/// Deinitialises the LPUART instance and both FlexIO UART channels.
///
/// After this call the peripherals are disabled and all driver state is reset.
/// Non-fatal status codes from the underlying driver are silently discarded.
///
/// # Safety
///
/// Must only be called after a successful [`init`].
pub unsafe fn deinit() {
    let _ = Lpuart_Uart_Ip_Deinit(LPUART_CHANNEL);
    let _ = Flexio_Uart_Ip_Deinit(FLEXIO_RX_CHANNEL);
    let _ = Flexio_Uart_Ip_Deinit(FLEXIO_TX_CHANNEL);
}

// =============================================================================
// Send
// =============================================================================

/// Transmits `buf` over `backend` and blocks until the transfer is complete.
///
/// Steps performed:
/// 1. Calls the driver's `AsyncSend` to kick off the non-blocking transfer.
/// 2. Spins on `GetTransmitStatus` / `GetStatus` until `SUCCESS` is returned
///    or the iteration limit ([`POLL_TIMEOUT`]) is exceeded.
///
/// # Errors
///
/// * [`CommError::InvalidArgument`] — `buf` is empty.
/// * [`CommError::WrongDirection`] — `backend` is [`UartBackend::FlexioRx`].
/// * [`CommError::LpuartError`] / [`CommError::FlexioError`] — driver failure.
/// * [`CommError::PollTimeout`] — hardware did not finish within the timeout.
pub fn send_data(backend: UartBackend, buf: &[u8]) -> Result<(), CommError> {
    if buf.is_empty() {
        return Err(CommError::InvalidArgument);
    }
    match backend {
        UartBackend::Lpuart   => send_lpuart(buf),
        UartBackend::FlexioTx => send_flexio(buf),
        UartBackend::FlexioRx => Err(CommError::WrongDirection),
    }
}

/// LPUART transmit path: async-send + poll-until-done.
fn send_lpuart(buf: &[u8]) -> Result<(), CommError> {
    let status = unsafe {
        Lpuart_Uart_Ip_AsyncSend(LPUART_CHANNEL, buf.as_ptr(), buf.len() as u32)
    };
    if status != LpuartStatus::Success {
        return Err(CommError::LpuartError(status));
    }

    let mut remaining: u32 = 0;
    let mut timeout = POLL_TIMEOUT;
    loop {
        let poll = unsafe { Lpuart_Uart_Ip_GetTransmitStatus(LPUART_CHANNEL, &mut remaining) };
        match poll {
            LpuartStatus::Success => return Ok(()),
            LpuartStatus::Busy => {
                timeout = timeout.checked_sub(1).ok_or(CommError::PollTimeout)?;
            }
            err => return Err(CommError::LpuartError(err)),
        }
    }
}

/// FlexIO TX transmit path: async-send + poll-until-done.
fn send_flexio(buf: &[u8]) -> Result<(), CommError> {
    let status = unsafe {
        Flexio_Uart_Ip_AsyncSend(FLEXIO_TX_CHANNEL, buf.as_ptr(), buf.len() as u32)
    };
    if status != FlexioStatus::Success {
        return Err(CommError::FlexioError(status));
    }

    let mut remaining: u32 = 0;
    let mut timeout = POLL_TIMEOUT;
    loop {
        let poll = unsafe { Flexio_Uart_Ip_GetStatus(FLEXIO_TX_CHANNEL, &mut remaining) };
        match poll {
            FlexioStatus::Success => return Ok(()),
            FlexioStatus::Busy => {
                timeout = timeout.checked_sub(1).ok_or(CommError::PollTimeout)?;
            }
            err => return Err(CommError::FlexioError(err)),
        }
    }
}

// =============================================================================
// Receive
// =============================================================================

/// Starts an asynchronous receive into `buf` over `backend` and blocks until
/// all bytes have been received.
///
/// Steps performed:
/// 1. Calls the driver's `AsyncReceive` to set up the non-blocking transfer.
/// 2. Spins on `GetReceiveStatus` / `GetStatus` until `SUCCESS` is returned
///    or the iteration limit ([`POLL_TIMEOUT`]) is exceeded.
///
/// # Errors
///
/// * [`CommError::InvalidArgument`] — `buf` is empty.
/// * [`CommError::WrongDirection`] — `backend` is [`UartBackend::FlexioTx`].
/// * [`CommError::LpuartError`] / [`CommError::FlexioError`] — driver failure.
/// * [`CommError::PollTimeout`] — hardware did not finish within the timeout.
pub fn receive_data(backend: UartBackend, buf: &mut [u8]) -> Result<(), CommError> {
    if buf.is_empty() {
        return Err(CommError::InvalidArgument);
    }
    match backend {
        UartBackend::Lpuart   => receive_lpuart(buf),
        UartBackend::FlexioRx => receive_flexio(buf),
        UartBackend::FlexioTx => Err(CommError::WrongDirection),
    }
}

/// LPUART receive path: async-receive + poll-until-done.
fn receive_lpuart(buf: &mut [u8]) -> Result<(), CommError> {
    let status = unsafe {
        Lpuart_Uart_Ip_AsyncReceive(LPUART_CHANNEL, buf.as_mut_ptr(), buf.len() as u32)
    };
    if status != LpuartStatus::Success {
        return Err(CommError::LpuartError(status));
    }

    let mut remaining: u32 = 0;
    let mut timeout = POLL_TIMEOUT;
    loop {
        let poll = unsafe { Lpuart_Uart_Ip_GetReceiveStatus(LPUART_CHANNEL, &mut remaining) };
        match poll {
            LpuartStatus::Success => return Ok(()),
            LpuartStatus::Busy => {
                timeout = timeout.checked_sub(1).ok_or(CommError::PollTimeout)?;
            }
            err => return Err(CommError::LpuartError(err)),
        }
    }
}

/// FlexIO RX receive path: async-receive + poll-until-done.
fn receive_flexio(buf: &mut [u8]) -> Result<(), CommError> {
    let status = unsafe {
        Flexio_Uart_Ip_AsyncReceive(FLEXIO_RX_CHANNEL, buf.as_mut_ptr(), buf.len() as u32)
    };
    if status != FlexioStatus::Success {
        return Err(CommError::FlexioError(status));
    }

    let mut remaining: u32 = 0;
    let mut timeout = POLL_TIMEOUT;
    loop {
        let poll = unsafe { Flexio_Uart_Ip_GetStatus(FLEXIO_RX_CHANNEL, &mut remaining) };
        match poll {
            FlexioStatus::Success => return Ok(()),
            FlexioStatus::Busy => {
                timeout = timeout.checked_sub(1).ok_or(CommError::PollTimeout)?;
            }
            err => return Err(CommError::FlexioError(err)),
        }
    }
}

// =============================================================================
// C-callable exports  (declared in include/hse_rust.h)
// =============================================================================

/// Maximum number of bytes accepted by a single send/receive call.
///
/// Callers that pass `len > MAX_TRANSFER_LEN` receive `false` immediately,
/// preventing an oversized transfer from stalling the UART driver.
pub const MAX_TRANSFER_LEN: u32 = 256;

// ── Helpers ───────────────────────────────────────────────────────────────────

/// Validates a TX pointer+length pair and builds an immutable slice.
///
/// Returns `None` (→ `false` to the C caller) when:
/// * `data` is null
/// * `len == 0` or `len > MAX_TRANSFER_LEN`
#[inline]
fn make_send_slice<'a>(data: *const u8, len: u32) -> Option<&'a [u8]> {
    if data.is_null() || len == 0 || len > MAX_TRANSFER_LEN {
        return None;
    }
    // SAFETY: caller guarantees `data` points to `len` valid, initialised bytes
    // and that the buffer will not be mutated for the duration of the call.
    Some(unsafe { core::slice::from_raw_parts(data, len as usize) })
}

/// Validates an RX pointer+length pair and builds a mutable slice.
///
/// Returns `None` (→ `false` to the C caller) when:
/// * `buf` is null
/// * `len == 0` or `len > MAX_TRANSFER_LEN`
#[inline]
fn make_recv_slice<'a>(buf: *mut u8, len: u32) -> Option<&'a mut [u8]> {
    if buf.is_null() || len == 0 || len > MAX_TRANSFER_LEN {
        return None;
    }
    // SAFETY: caller guarantees `buf` points to `len` writable bytes and that
    // no other reference to the same memory exists during this call.
    Some(unsafe { core::slice::from_raw_parts_mut(buf, len as usize) })
}

// ── send_to_ap / send_to_ap2 ──────────────────────────────────────────────────

/// Transmit `len` bytes from `data` to the application processor over LPUART.
///
/// Returns `true` on success, `false` on any error (null pointer, oversized
/// transfer, or driver failure).
///
/// C declaration (hse_rust.h):
///   `bool send_to_ap(const uint8_t *data, uint32_t len);`
#[no_mangle]
pub extern "C" fn send_to_ap(data: *const u8, len: u32) -> bool {
    let buf = match make_send_slice(data, len) {
        Some(s) => s,
        None => return false,
    };
    send_data(UartBackend::Lpuart, buf).is_ok()
}

/// Transmit `len` bytes from `data` to the application processor, with
/// backend selection.
///
/// When `use_flexio` is `false` (0) the data is sent over LPUART; when
/// `true` (non-zero) it is sent over the FlexIO TX channel.
///
/// Returns `true` on success, `false` on any error.
///
/// C declaration (hse_rust.h):
///   `bool send_to_ap2(const uint8_t *data, uint32_t len, bool use_flexio);`
#[no_mangle]
pub extern "C" fn send_to_ap2(data: *const u8, len: u32, use_flexio: bool) -> bool {
    let buf = match make_send_slice(data, len) {
        Some(s) => s,
        None => return false,
    };
    let backend = if use_flexio {
        UartBackend::FlexioTx
    } else {
        UartBackend::Lpuart
    };
    send_data(backend, buf).is_ok()
}

// ── recv_from_ap / recv_from_ap2 ─────────────────────────────────────────────

/// Receive `len` bytes from the application processor into `buf` over LPUART.
///
/// Returns `true` on success, `false` on any error (null pointer, oversized
/// transfer, or driver failure).
///
/// C declaration (hse_rust.h):
///   `bool recv_from_ap(uint8_t *buf, uint32_t len);`
#[no_mangle]
pub extern "C" fn recv_from_ap(buf: *mut u8, len: u32) -> bool {
    let slice = match make_recv_slice(buf, len) {
        Some(s) => s,
        None => return false,
    };
    receive_data(UartBackend::Lpuart, slice).is_ok()
}

/// Receive `len` bytes from the application processor into `buf`, with
/// backend selection.
///
/// When `use_flexio` is `false` (0) data is received via LPUART; when
/// `true` (non-zero) data is received via the FlexIO RX channel.
///
/// Returns `true` on success, `false` on any error.
///
/// C declaration (hse_rust.h):
///   `bool recv_from_ap2(uint8_t *buf, uint32_t len, bool use_flexio);`
#[no_mangle]
pub extern "C" fn recv_from_ap2(buf: *mut u8, len: u32, use_flexio: bool) -> bool {
    let slice = match make_recv_slice(buf, len) {
        Some(s) => s,
        None => return false,
    };
    let backend = if use_flexio {
        UartBackend::FlexioRx
    } else {
        UartBackend::Lpuart
    };
    receive_data(backend, slice).is_ok()
}

// ── req_save_data / req_saved_data ────────────────────────────────────────────

/// Request that the application processor persists `len` bytes from `data`.
///
/// Currently implemented as a send over LPUART.  The protocol-level
/// framing (command byte, acknowledgement, etc.) will be layered on top
/// in a future revision.
///
/// Returns `true` on success, `false` on any error.
///
/// C declaration (hse_rust.h):
///   `bool req_save_data(const uint8_t *data, uint32_t len);`
#[no_mangle]
pub extern "C" fn req_save_data(data: *const u8, len: u32) -> bool {
    let buf = match make_send_slice(data, len) {
        Some(s) => s,
        None => return false,
    };
    send_data(UartBackend::Lpuart, buf).is_ok()
}

/// Request that the application processor returns previously saved data into
/// `buf` (up to `len` bytes).
///
/// Currently implemented as a receive over LPUART.  The protocol-level
/// framing will be layered on top in a future revision.
///
/// Returns `true` on success, `false` on any error.
///
/// C declaration (hse_rust.h):
///   `bool req_saved_data(uint8_t *buf, uint32_t len);`
#[no_mangle]
pub extern "C" fn req_saved_data(buf: *mut u8, len: u32) -> bool {
    let slice = match make_recv_slice(buf, len) {
        Some(s) => s,
        None => return false,
    };
    receive_data(UartBackend::Lpuart, slice).is_ok()
}

// =============================================================================
// Secure communication layer — AES-CBC-128 encryption + AES-CMAC-128 integrity
// =============================================================================
//
// Wire frame layout (encrypt-then-MAC):
//
//   ┌─────────┬────────────────────────┬──────────┐
//   │ IV 16 B │ Ciphertext  (ct_len B) │ CMAC 16B │
//   └─────────┴────────────────────────┴──────────┘
//
//   ct_len == plaintext_len  (no padding added; caller must align to 16 B)
//   CMAC is computed over the contiguous region:  IV || Ciphertext
//   On-wire byte count:  ct_len + 32
//
// Security properties:
//   • Confidentiality: AES-CBC-128 with a fresh random IV per frame.
//   • Integrity + authenticity: full 128-bit CMAC tag over IV and ciphertext
//     (encrypt-then-MAC prevents decryption oracle attacks).
//   • The CMAC is verified BEFORE decryption; any tampered frame is rejected
//     without ever decrypting a single byte.

const AES_BLOCK_SIZE: usize = 16;
const CMAC_TAG_SIZE: usize = 16;
const IV_SIZE: usize = 16;

/// Maximum plaintext bytes supported per secure call (14 × 16).
///
/// The corresponding on-wire frame is `MAX_SECURE_PLAINTEXT + 32` bytes, which
/// fits exactly within the [`MAX_TRANSFER_LEN`] limit of 256 bytes.
pub const MAX_SECURE_PLAINTEXT: usize = 224;

/// `HSE_INVALID_KEY_HANDLE` sentinel — key slot not yet initialised.
const INVALID_KEY_HANDLE: u32 = 0xFFFF_FFFF;

/// Key handle for the CBC cipher key, stored after a successful [`secure_init`].
static CIPHER_KEY_HANDLE: AtomicU32 = AtomicU32::new(INVALID_KEY_HANDLE);

/// Key handle for the CMAC authentication key, stored after a successful [`secure_init`].
static MAC_KEY_HANDLE: AtomicU32 = AtomicU32::new(INVALID_KEY_HANDLE);

// =============================================================================
// Error type
// =============================================================================

/// Errors that can be returned by the secure-communication layer.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum SecureCommError {
    /// Underlying UART transport error.
    Transport(CommError),
    /// HSE rejected a key-import request during [`secure_init`].
    KeyLoadFailed(HseError),
    /// HSE AES-CBC encrypt or decrypt operation failed.
    CipherFailed(HseError),
    /// HSE CMAC tag-generation operation failed.
    MacGenerateFailed(HseError),
    /// CMAC tag verification failed: frame was tampered or the wrong key was used.
    MacVerifyFailed,
    /// Plaintext length is zero, not a multiple of 16,
    /// or exceeds [`MAX_SECURE_PLAINTEXT`].
    InvalidLength,
    /// [`secure_init`] has not been called or it returned an error.
    NotInitialized,
}

// =============================================================================
// Initialisation
// =============================================================================

/// Ensures the HSE key catalog is formatted and the software key-handle
/// allocator (HKF) is initialised, then loads the two AES-128 keys required
/// by the secure channel into HSE RAM slots.
///
/// Must be called **once** before any [`secure_send`] or [`secure_receive`] call.
/// Calling it again re-imports the keys into the same slots, which is safe but
/// interrupts any in-flight operation that relies on the old key material.
///
/// # Catalog-setup sequence
///
/// 1. `IsKeyCatalogFormatted()` — checks `HSE_STATUS_INSTALL_OK`.
/// 2. If **not** yet formatted: `FormatKeyCatalogs_()` lays out both the NVM and
///    RAM catalogs using the built-in `HSE_DEMO_*_KEY_CATALOG_CFG` tables and
///    then calls `ParseKeyCatalogs()` internally (initialises the HKF allocator).
/// 3. If **already** formatted: `ParseKeyCatalogs()` is called alone to (re-)
///    initialise the HKF allocator without disturbing the stored NVM keys.
///
/// # Key-slot assignments
///
/// The RAM catalog group-1 contains 10 × AES-128 slots (index from the
/// `HSE_DEMO_RAM_KEY_CATALOG_CFG` definition in `hse_b_catalog_formatting.h`).
///
/// | Purpose       | HSE RAM group | Slot | Handle       | Allowed modes |
/// |---------------|---------------|------|--------------|---------------|
/// | CBC cipher    | 1             | 0    | `0x020100`   | CBC only      |
/// | CMAC          | 1             | 1    | `0x020101`   | Any (MAC use) |
///
/// # Safety
///
/// * `cipher_key` and `mac_key` must each point to exactly 16 valid, initialised
///   bytes for the duration of this call.
/// * This function calls HSE firmware via the MU interface; it must not be
///   called from an interrupt context.
pub unsafe fn secure_init(
    cipher_key: &[u8; 16],
    mac_key: &[u8; 16],
) -> Result<(), SecureCommError> {
    // Step 1: Ensure the HSE key catalog is formatted and HKF is initialised.
    //
    // • IsKeyCatalogFormatted checks the HSE_STATUS_INSTALL_OK status bit.
    // • If the catalog was never formatted (e.g. first boot), FormatKeyCatalogs_
    //   formats both the NVM and RAM catalogs and calls ParseKeyCatalogs() itself.
    // • If already formatted (subsequent boots), only ParseKeyCatalogs() is
    //   called so that existing NVM keys are preserved.
    if IsKeyCatalogFormatted() == 0 {
        let resp = FormatKeyCatalogs_();
        if !resp.is_ok() {
            return Err(SecureCommError::KeyLoadFailed(HseError::Raw(resp.0)));
        }
        // FormatKeyCatalogs_ already calls ParseKeyCatalogs internally.
    } else {
        let resp = ParseKeyCatalogs();
        if !resp.is_ok() {
            return Err(SecureCommError::KeyLoadFailed(HseError::Raw(resp.0)));
        }
    }

    // Step 2: Import AES-CBC cipher key into RAM group-1 slot-0.
    hse::import_plain_sym_key(
        RAM_AES_GROUP1_SLOT0,
        key_flags::ENCRYPT_DECRYPT,
        128,
        1 << 2, // restrict to CBC mode (HSE_KU_AES_BLOCK_MODE_CBC)
        cipher_key,
    ).map_err(SecureCommError::KeyLoadFailed)?;
    CIPHER_KEY_HANDLE.store(RAM_AES_GROUP1_SLOT0, Ordering::Relaxed);

    // Step 3: Import AES-CMAC key into RAM group-1 slot-1.
    // aes_block_mode_mask = 0 means any block mode is allowed; the HSE enforces
    // SIGN/VERIFY usage flags to restrict this key to MAC operations only.
    hse::import_plain_sym_key(
        RAM_AES_GROUP1_SLOT1,
        key_flags::SIGN_VERIFY,
        128,
        0, // any block mode; usage flags restrict to MAC
        mac_key,
    ).map_err(SecureCommError::KeyLoadFailed)?;
    MAC_KEY_HANDLE.store(RAM_AES_GROUP1_SLOT1, Ordering::Relaxed);

    Ok(())
}

// =============================================================================
// Secure send
// =============================================================================

/// Encrypts `plaintext` with AES-CBC-128, appends a 16-byte AES-CMAC-128 tag,
/// and transmits the resulting frame over `backend`.
///
/// Frame layout: `IV(16) || AES-CBC(plaintext) || CMAC(IV||ciphertext)`
///
/// # Errors
///
/// * [`SecureCommError::NotInitialized`] — [`secure_init`] was not called.
/// * [`SecureCommError::InvalidLength`]  — `plaintext` is empty, not a multiple
///   of 16 bytes, or longer than [`MAX_SECURE_PLAINTEXT`] (224 bytes).
/// * [`SecureCommError::CipherFailed`]   — HSE AES or RNG error.
/// * [`SecureCommError::MacGenerateFailed`] — HSE CMAC error.
/// * [`SecureCommError::Transport`]      — UART send error.
pub fn secure_send(backend: UartBackend, plaintext: &[u8]) -> Result<(), SecureCommError> {
    let n = plaintext.len();
    if n == 0 || n % AES_BLOCK_SIZE != 0 || n > MAX_SECURE_PLAINTEXT {
        return Err(SecureCommError::InvalidLength);
    }

    let cipher_handle = CIPHER_KEY_HANDLE.load(Ordering::Relaxed);
    let mac_handle = MAC_KEY_HANDLE.load(Ordering::Relaxed);
    if cipher_handle == INVALID_KEY_HANDLE || mac_handle == INVALID_KEY_HANDLE {
        return Err(SecureCommError::NotInitialized);
    }

    // Stack-allocate the maximum frame: IV(16) + ciphertext(224) + CMAC(16) = 256 B.
    let mut frame = [0u8; IV_SIZE + MAX_SECURE_PLAINTEXT + CMAC_TAG_SIZE];
    let frame_len = IV_SIZE + n + CMAC_TAG_SIZE;

    // 1. Fill IV with cryptographically strong random bytes.
    hse::get_rng_drg4(&mut frame[..IV_SIZE]).map_err(SecureCommError::CipherFailed)?;

    // 2. Encrypt plaintext → frame[IV_SIZE..IV_SIZE+n].
    //    Copy the IV to a local array so we can hold an immutable borrow on
    //    frame[0..16] while mutably borrowing frame[16..16+n].
    let iv: [u8; IV_SIZE] = frame[..IV_SIZE].try_into().unwrap();
    hse::aes_cbc_encrypt(cipher_handle, &iv, plaintext, &mut frame[IV_SIZE..IV_SIZE + n])
        .map_err(SecureCommError::CipherFailed)?;

    // 3. Compute CMAC over frame[0..IV_SIZE+n]  (IV || ciphertext, contiguous).
    //    split_at_mut gives non-overlapping borrows: mac_input (read) and
    //    tag_dest (write) into the same frame array.
    {
        let (mac_input, tag_dest) = frame.split_at_mut(IV_SIZE + n);
        let tag_arr =
            <&mut [u8; CMAC_TAG_SIZE]>::try_from(&mut tag_dest[..CMAC_TAG_SIZE]).unwrap();
        hse::aes_cmac_generate(mac_handle, mac_input, tag_arr)
            .map_err(SecureCommError::MacGenerateFailed)?;
    }

    // 4. Transmit the complete frame.
    send_data(backend, &frame[..frame_len]).map_err(SecureCommError::Transport)
}

// =============================================================================
// Secure receive
// =============================================================================

/// Receives a secure frame, verifies its AES-CMAC-128 tag, then decrypts the
/// ciphertext into `plaintext_out`.
///
/// The caller must supply the expected ciphertext length (`expected_ct_len`),
/// which equals the plaintext length used by the sender (no padding is added).
/// The function receives exactly `expected_ct_len + 32` bytes from `backend`.
///
/// **Decryption happens only after the CMAC is verified** (encrypt-then-MAC).
///
/// # Parameters
///
/// * `backend`         — UART backend to receive from.
/// * `plaintext_out`   — output buffer; must be ≥ `expected_ct_len` bytes.
/// * `expected_ct_len` — expected ciphertext/plaintext length in bytes;
///                       must be a non-zero multiple of 16 and ≤ [`MAX_SECURE_PLAINTEXT`].
///
/// # Errors
///
/// * [`SecureCommError::NotInitialized`] — [`secure_init`] was not called.
/// * [`SecureCommError::InvalidLength`]  — invalid `expected_ct_len` or
///   `plaintext_out` is too small.
/// * [`SecureCommError::Transport`]      — UART receive error.
/// * [`SecureCommError::MacVerifyFailed`] — CMAC mismatch; frame rejected.
/// * [`SecureCommError::CipherFailed`]   — HSE AES decrypt error.
///
/// # Returns
///
/// On success, returns `Ok(expected_ct_len)` (plaintext byte count written to
/// `plaintext_out`).
pub fn secure_receive(
    backend: UartBackend,
    plaintext_out: &mut [u8],
    expected_ct_len: usize,
) -> Result<usize, SecureCommError> {
    if expected_ct_len == 0
        || expected_ct_len % AES_BLOCK_SIZE != 0
        || expected_ct_len > MAX_SECURE_PLAINTEXT
        || plaintext_out.len() < expected_ct_len
    {
        return Err(SecureCommError::InvalidLength);
    }

    let cipher_handle = CIPHER_KEY_HANDLE.load(Ordering::Relaxed);
    let mac_handle = MAC_KEY_HANDLE.load(Ordering::Relaxed);
    if cipher_handle == INVALID_KEY_HANDLE || mac_handle == INVALID_KEY_HANDLE {
        return Err(SecureCommError::NotInitialized);
    }

    let frame_len = IV_SIZE + expected_ct_len + CMAC_TAG_SIZE;
    let mut frame = [0u8; IV_SIZE + MAX_SECURE_PLAINTEXT + CMAC_TAG_SIZE];

    // 1. Receive the full frame.
    receive_data(backend, &mut frame[..frame_len]).map_err(SecureCommError::Transport)?;

    // 2. Verify CMAC over frame[0..IV_SIZE+ct_len]  (IV || ciphertext).
    //    The tag sits at frame[IV_SIZE+ct_len..frame_len].
    //    We verify BEFORE decrypting to prevent decryption-oracle attacks.
    let tag_arr = <&[u8; CMAC_TAG_SIZE]>::try_from(
        &frame[IV_SIZE + expected_ct_len..IV_SIZE + expected_ct_len + CMAC_TAG_SIZE],
    ).unwrap();
    hse::aes_cmac_verify(mac_handle, &frame[..IV_SIZE + expected_ct_len], tag_arr)
        .map_err(|_| SecureCommError::MacVerifyFailed)?;

    // 3. Decrypt frame[IV_SIZE..IV_SIZE+ct_len] → plaintext_out.
    //    IV and ciphertext are both immutable borrows of frame; plaintext_out
    //    is a separate external buffer — no aliasing concern.
    let iv_arr = <&[u8; IV_SIZE]>::try_from(&frame[..IV_SIZE]).unwrap();
    let ct = &frame[IV_SIZE..IV_SIZE + expected_ct_len];
    hse::aes_cbc_decrypt(cipher_handle, iv_arr, ct, &mut plaintext_out[..expected_ct_len])
        .map_err(SecureCommError::CipherFailed)?;

    Ok(expected_ct_len)
}

// =============================================================================
// C-callable secure-channel exports
// =============================================================================

// The SHE example CBC and CMAC keys from hse_host_wrappers.c
// (SheLoadNVMKey_CBC / SheLoadNVMKey_CMAC).
const SHE_CBC_KEY: [u8; 16] = [
    0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6,
    0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f, 0x3c,
];
const SHE_CMAC_KEY: [u8; 16] = [
    0x2b, 0x7e, 0x15, 0x16, 0x28, 0xae, 0xd2, 0xa6,
    0xab, 0xf7, 0x15, 0x88, 0x09, 0xcf, 0x4f, 0x3c,
];

/// Initialises the secure channel using the constant keys from the SHE
/// example project (`SheLoadNVMKey_CBC` / `SheLoadNVMKey_CMAC` in
/// `hse_host_wrappers.c`).
///
/// This is a convenience wrapper around [`secure_comm_init`] that does not
/// require the caller to supply key bytes — the keys are compiled in.
///
/// Returns `true` on success, `false` if HSE key-import fails.
///
/// C declaration (hse_rust.h):
///   `bool secure_comm_init_she_keys(void);`
#[no_mangle]
pub unsafe extern "C" fn secure_comm_init_she_keys() -> bool {
    secure_init(&SHE_CBC_KEY, &SHE_CMAC_KEY).is_ok()
}

/// Loads AES-128 keys for the secure channel.
///
/// Both `cipher_key` and `mac_key` must point to exactly 16 valid bytes.
/// Returns `true` on success, `false` if HSE key-import fails or a pointer
/// is null.
///
/// C declaration (hse_rust.h):
///   `bool secure_comm_init(const uint8_t *cipher_key, const uint8_t *mac_key);`
#[no_mangle]
pub unsafe extern "C" fn secure_comm_init(cipher_key: *const u8, mac_key: *const u8) -> bool {
    if cipher_key.is_null() || mac_key.is_null() {
        return false;
    }
    // SAFETY: caller guarantees each pointer addresses exactly 16 valid bytes.
    let ck = &*(cipher_key as *const [u8; 16]);
    let mk = &*(mac_key as *const [u8; 16]);
    secure_init(ck, mk).is_ok()
}

/// Encrypts and sends `len` bytes of plaintext over LPUART.
///
/// `len` must be a non-zero multiple of 16 and ≤ 224.
/// Returns `true` on success, `false` on any crypto or transport error.
///
/// C declaration (hse_rust.h):
///   `bool secure_send_to_ap_encrypted(const uint8_t *data, uint32_t len);`
#[no_mangle]
pub extern "C" fn secure_send_to_ap_encrypted(data: *const u8, len: u32) -> bool {
    if data.is_null() || len == 0 || len > MAX_SECURE_PLAINTEXT as u32 {
        return false;
    }
    // SAFETY: pointer is non-null and len > 0 checked above.
    let buf = unsafe { core::slice::from_raw_parts(data, len as usize) };
    secure_send(UartBackend::Lpuart, buf).is_ok()
}

/// Receives a secure frame and decrypts it into `buf`.
///
/// Receives exactly (`expected_ct_len` + 32) bytes, verifies CMAC, then
/// decrypts.  On success `*out_len` is set to `expected_ct_len`.
/// Returns `true` on success, `false` on any error.
///
/// C declaration (hse_rust.h):
///   `bool secure_recv_from_ap_encrypted(
///       uint8_t *buf, uint32_t expected_ct_len, uint32_t *out_len);`
#[no_mangle]
pub extern "C" fn secure_recv_from_ap_encrypted(
    buf: *mut u8,
    expected_ct_len: u32,
    out_len: *mut u32,
) -> bool {
    if buf.is_null()
        || out_len.is_null()
        || expected_ct_len == 0
        || expected_ct_len > MAX_SECURE_PLAINTEXT as u32
    {
        return false;
    }
    // SAFETY: caller guarantees buf points to at least expected_ct_len writable bytes.
    let slice = unsafe { core::slice::from_raw_parts_mut(buf, expected_ct_len as usize) };
    match secure_receive(UartBackend::Lpuart, slice, expected_ct_len as usize) {
        Ok(n) => {
            unsafe { *out_len = n as u32 };
            true
        }
        Err(_) => false,
    }
}
